//USER REGISTER
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
export const OFF_MODAL = "OFF_MODAL";
//USER REGISTER ACTIVE
export const ACTIVE_USER_ACCOUNT_REUQEST = "ACTIVE_USER_ACCOUNT_REUQEST";
export const ACTIVE_USER_ACCOUNT_SUCCESS = "ACTIVE_USER_ACCOUNT_SUCCESS";
export const ACTIVE_USER_ACCOUNT_FAILURE = "ACTIVE_USER_ACCOUNT_FAILURE";
//get list of categories
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
//get main Slider
export const GET_SLIDER_REQUEST = "GET_SLIDER_REQUEST";
export const GET_SLIDER_SUCCESS = "GET_SLIDER_SUCCESS";
export const GET_SLIDER_FAILURE = "GET_SLIDER_FAILURE";
