//handle Overlay
export const OPEN_OVERLAY = "OPEN_OVERLAY";
export const CLOSE_OVERLAY = "CLOSE_OVERLAY";

//USER REGISTER
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
export const OFF_MODAL = "OFF_MODAL";
//USER REGISTER ACTIVE
export const ACTIVE_USER_ACCOUNT_REUQEST = "ACTIVE_USER_ACCOUNT_REUQEST";
export const ACTIVE_USER_ACCOUNT_SUCCESS = "ACTIVE_USER_ACCOUNT_SUCCESS";
export const ACTIVE_USER_ACCOUNT_FAILURE = "ACTIVE_USER_ACCOUNT_FAILURE";
//LOGIN USER
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
//get list of categories
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
//get main Slider
export const GET_SLIDER_REQUEST = "GET_SLIDER_REQUEST";
export const GET_SLIDER_SUCCESS = "GET_SLIDER_SUCCESS";
export const GET_SLIDER_FAILURE = "GET_SLIDER_FAILURE";
//get banners
export const GET_BANNERS_REQUEST = "GET_BANNERS_REQUEST";
export const GET_BANNERS_SUCCESS = "GET_BANNERS_SUCCESS";
export const GET_BANNERS_FAILURE = "GET_BANNERS_FAILURE";
//get products
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
//get products best selling
export const GET_BEST_SELLING_PRODUCTS_REQUEST =
  "GET_BEST_SELLING_PRODUCTS_REQUEST";
export const GET_BEST_SELLING_PRODUCTS_SUCCESS =
  "GET_BEST_SELLING_PRODUCTS_SUCCESS";
export const GET_BEST_SELLING_PRODUCTS_FAILURE =
  "GET_BEST_SELLING_PRODUCTS_FAILURE";
//get products by sort
export const GET_NEW_PRODUCTS_REQUEST = "GET_NEW_PRODUCTS_REQUEST";
export const GET_NEW_PRODUCTS_SUCCESS = "GET_NEW_PRODUCTS_SUCCESS";
export const GET_NEW_PRODUCTS_FAILURE = "GET_NEW_PRODUCTS_FAILURE";
//get product detils
export const GET_PRODUCTS_DETAILS_REQUEST = "GET_PRODUCTS_DETAILS_REQUEST";
export const GET_PRODUCTS_DETAILS_SUCCESS = "GET_PRODUCTS_DETAILS_SUCCESS";
export const GET_PRODUCTS_DETAILS_FAILURE = "GET_PRODUCTS_DETAILS_FAILURE";
//get product detils
export const GET_SINGLE_PRODUCT_DETAILS_REQUEST =
  "GET_PRODUCTS_DETAILS_REQUEST";
export const GET_SINGLE_PRODUCT_DETAILS_SUCCESS =
  "GET_SINGLE_PRODUCT_DETAILS_SUCCESS";
export const GET_SINGLE_PRODUCT_DETAILS_FAILURE =
  "GET_SINGLE_PRODUCT_DETAILS_FAILURE";
//ADD TO CART
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST";
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAILURE = "GET_CART_ITEMS_FAILURE";
